### ISSUE TITLE
Cannot upgrade image_picker: ^0.8.1+3

### ISSUE THREAD

**Issue by ccamba** [jayeshpansheriya/image_picker_type#4]
Because image_picker_type 1.0.1 depends on image_picker ^0.7.5+2 and no versions of image_picker_type match >1.0.1 <2.0.0, image_picker_type ^1.0.1 requires image_picker ^0.7.5+2.
So, because xxxx depends on both image_picker ^0.8.1+3 and image_picker_type ^1.0.1, version solving failed.
pub get failed (1; So, because xxxx depends on both image_picker ^0.8.1+3 and image_picker_type ^1.0.1, version solving failed.)

**Comment by jayeshindianic** [comment]
@ccamba use can override package version like this:
```
dependency_overrides:
  image_picker: version
```
otherwise you can use latest version of plugin : image_picker_type 1.0.2

**Comment by ccamba** [comment]
@jayeshindianic thanks, works !
